let obj={
    "Alluri Sitharama Raju":['Araku Valley',
                             'Paderu',
                            'Rampachodavaram'],
    "Annamayya":['Rajampet',
                'Kodur',
                'Rayachoti',
                'Madanapalle'],
    "Anakapalli":['Chodavaram',
                    'Madugula',
                    'Anakapalli',
                    'Pendurthi',
                    'Elamanchili',
                    'Payakaraopet',
                    'Narsipatnam'],
    "Anantapuramu":[
        'Rayadurg',
        'Uravakonda',
        'Guntakal',
        'Tadpatri',
        'Singanamala',
        'Anantapur Urban',
        'Kalyandurg',
        'Raptadu',
    ],
    "Bapatla":[
        'Vemuru (SC)',
        'Repalle',
        'Bapatla',
        'Parchur',
        'Addanki',
        'Chirala',
        'Santhanuthalapadu',
    ],
}