districts = [
    "Alluri Sitharama Raju",
    "Annamayya",
    "Anakapalli",
    "Anantapuramu",
    "Bapatla",
    "Chittoor",
    "Dr. B.R. Ambedkar Konaseema",
    "East Godavari",
    "Eluru",
    "Guntur",
    "Kakinada",
    "Krishna",
    "Kurnool",
    "Nandyal",
    "NTR",
    "Palnadu",
    "Parvathipuram Manyam",
    "Prakasam",
    "Sri Potti Sriramulu Nellore",
    "Sri Sathya Sai",
    "Srikakulam",
    "Tirupati",
    "Vizianagaram",
    "Visakhapatnam",
    "West Godavari",
    "YSR"
]
