ycp_candidates = {
    "Achanta": "Cherukuvada Sriranganadha Raju",
    "Adoni": "Y. Sai Prasad Reddy",
    "Allagadda": "Gangula Brijendra Reddy (Nani)",
    "Alur": "P Jayaram",
    "Amadalavalasa": "Thammineni Seetharam",
    "Amalapuram": "Viswarupu Pinipe",
    "Anakapalli": "A V S S Amarnath Gudivada",
    "Anantapur Urban": "Anantha Venkatarami Reddy",
    "Anaparthy": "Doctor. Sathi Suryanarayana Reddy",
    "Araku Valley": "Chetti. Palguna",
    "Atmakur": "Mekapati Goutham Reddy",
    "Avanigadda": "Ramesh Babu Simhadri",
    "Badvel": "Dr. G. Venkata Subbaiah",
    "Banaganapalle": "Katasani Rami Reddy",
    "Bapatla": "Kona Raghupathi",
    "Bhimavaram": "Grandhi Srinivas",
    "Bhimli": "Muttamsetti Srinivasarao (AVANTHI SRINIVAS)",
    "Bobbili": "Sambangi Venkatachina Appala Naidu",
    "Chandragiri": "Dr.Chevireddy Bhaskar Reddy",
    "Cheepurupalli": "Botcha Satyanarayana",
    "Chilakaluripet": "Rajini Vidadala",
    "Chintalapudi": "Vunnamatla Rakada Eliza",
    "Chittoor": "Aranii Srenevasulu (Jangalapalli)",
    "Chodavaram": "Karanam Dharmasri",
    "Darsi": "Maddisetty Venugopal",
    "Denduluru": "Abbaya Chowdary Kothari",
    "Dharmavaram": "Kethireddy Venkatarami Reddy",
    "Dhone": "Buggana Raja Reddy",
    "Elamanchili": "Uppalapati Venkata Ramanamurthy Raju",
    "Eluru": "Alla Kali Krishna Srinivas",
    "Etcherla": "Gorle. Kiran Kumar",
    "Gajapathinagaram": "Appalanarasayya Botcha",
    "Gajuwaka": "Nagireddy Tippala",
    "Gangadhara Nellore": "K. Narayana Swamy",
    "Gannavaram": "Kondeti Chitti Babu",
    "Giddalur": "Anna Rambabu",
    "Gopalapuram": "Venkatrao Talari",
    "Gudivada": "Kodali Sri Venkateswara Rao",
    "Gudur": "Velagapalli Varaprasad Rao",
    "Guntakal": "Y. Venkatarama Reddy",
    "Guntur East": "Mohammed Mustafa Shaik",
    "Gurazala": "Kasu Mahesh Reddy",
    "Jaggampeta": "Jyothula Naga Veera Venkata Vishnu Satya Marthanda Rao",
    "Jaggayyapeta": "Udayabhanu Samineni",
    "Jammalamadugu": "Mule Sudheer Reddy",
    "Kadapa": "Amzath Basha Shaik Bepari",
    "Kadiri": "P.V. Sidda Reddy",
    "Kaikalur": "Dulam Nageswara Rao",
    "Kakinada City": "Dwarampudi Chandra Sekhara Reddy",
    "Kakinada Rural": "Kurasala Kannababu",
    "Kalyandurg": "K.V. Usha Sricharan",
    "Kamalapuram": "Pochimareddy Ravindranath Reddy",
    "Kandukur": "Maheedhar Reddy Manugunta",
    "Kanigiri": "Burra Madhu Sudhan Yadav",
    "Kavali": "Ramireddy Pratap Kumar Reddy",
    "Kodumur": "Jaradoddi Sudhakar",
    "Kodur": "Koramutla Sreenivasulu",
    "Kothapeta": "Chirla Jaggireddy",
    "Kovur": "Nallapareddy Prasanna Kumar Reddy",
    "Kovvur": "Taneti Vanita",
    "Kurnool": "Abdul Hafeez Khan",
    "Kurupam": "Pushpasreevani . Pamula",
    "Macherla": "Ramakrishnareddy Pinnelli",
    "Machilipatnam": "Perni Venkataramaiah (NANI)",
    "Madakasira": "M Thippeswamy",
    "Madanapalle": "Mohammed Nawaz Basha",
    "Mangalagiri": "Alla Rama Krishna Reddy (RK)",
    "Mantralayam": "Y. Balanagi Reddy",
    "Markapuram": "Kunduru Nagarjuna Reddy",
    "Mummidivaram": "Ponnada Venkata Satish Kumar",
    "Mydukur": "Raghurami Reddy Settipally",
    "Mylavaram": "Vasantha Venkata Krishna Prasad",
    "Nagari": "R.K. Roja",
    "Nandigama": "Monditoka Jagan Mohana Rao",
    "Nandikotkur": "Thoguru Arthur",
    "Nandyal": "Shilpa Ravi Chandra Kishore Reddy",
    "Narasannapeta": "Dharmana Krishna Das",
    "Narasapuram": "Mudunuri Prasada Raju",
    "Narasaraopet": "Gopireddy Srinivasareddy",
    "Narsipatnam": "Uma Sankara Ganesh Petla",
    "Nellimarla": "Appala Naidu Baddukonda",
    "Nellore City": "Anil Kumar Poluboina",
    "Nellore Rural": "Kotamreddy Sridhar Reddy",
    "Nidadavole": "G. Srinivas Naidu",
    "Nuzvid": "Meka Venkata Pratap Apparao",
    "Ongole": "Balineni Srinivasa Reddy (VASU)",
    "Paderu": "Bhagya Lakshmi Kottagulli",
    "Palakonda (ST)": "Viswasarayi Kalavathi",
    "Palamaner": "N Venkate Gowda",
    "Palasa": "Appalaraju Seediri",
    "Pamarru": "Anil Kumar Kaile",
    "Panyam": "Katasani Rambhupal Reddy",
    "Parvathipuram": "Alajangi Jogarao",
    "Pathapatnam": "Reddy Shanthi",
    "Pattikonda": "Kangati Sreedevi",
    "Payakaraopeta": "Golla Baburao",
    "Pedakurapadu": "Sankara Rao Namburu",
    "Pedana": "Jogi Ramesh",
    "Penamaluru": "Kolusu Partha Sarathy",
    "Pendurthi": "Annamreddy Adeep Raj",
    "Penukonda": "Malagundla Sankaranarayana",
    "Pileru": "Chinthala Ramachandra Reddy",
    "Pithapuram": "Dorababu Pendem",
    "Polavaram": "Tellam Bala Raju",
    "Ponnur": "Venkatroshaiah Kilari",
    "Prathipadu": "Sri Purnachandra Prasad Parvatha",
    "Prathipadu (SC)": "Mekathoti Sucharitha",
    "Proddatur": "Rachamallu Siva Prasad Reddy",
    "Pulivendla": "Yeduguri Sandinti Jagan Mohan Reddy",
    "Punganur": "Peddireddi Ramachandra Reddy",
    "Puthalapattu": "M. Babu",
    "Puttaparthi": "Duddukunta Sreedhar Reddy",
    "Rajam (SC)": "Kambala Jogulu",
    "Rajampet": "Meda Venkata Mallikarjuna Reddy",
    "Rajanagaram": "Jakkampudi Raja",
    "Ramachandrapuram": "Chelluboyina Srinivasa Venugopalakrishna",
    "Rampachodavaram": "Nagulapalli Dhanalakshmi",
    "Raptadu": "Thopudurthi Prakash Reddy",
    "Rayachoti": "Gadikota. Srikanth Reddy",
    "Rayadurg": "Kapu Ramachandra Reddy",
    "Salur": "Peedika. Rajanna Dora",
    "Santhanuthalapadu": "T.J.R. Sudhakar Babu",
    "Sarvepalli": "Kakani Govardhan Reddy",
    "Sattenapalli": "Ambati Rambabu",
    "Satyavedu": "Adimulam Koneti",
    "Singanamala": "Padmavathy Jonnalagadda",
    "Srikakulam": "Dharmana Prasada Rao",
    "Srikalahasti": "Madhusudhan Reddy Biyyapu",
    "Srisailam": "Silpa Chakrapani Reddy",
    "Srungavarapukota": "Kadubandi Srinivasa Rao",
    "Sullurpeta": "Kiliveti Sanjeevaiah",
    "Tadepalligudem": "Kottu Satyanarayana",
    "Tadikonda (SC)": "Vundavalli Sridevi",
    "Tadipatri": "K. Pedda Reddy",
    "Tanuku": "Karumuri Venkata Nageswara Rao",
    "Tenali": "Annabathuni Siva Kumar",
    "Thamballapalle": "Peddireddy Dwarakanatha Reddy",
    "Tirupati": "Bhumana Karunakar Reddy",
    "Tiruvuru": "Kokkiligadda Rakshana Nidhi",
    "Tuni": "Dadisetti Raja",
    "Udayagiri": "Mekapati Chandra Sekhar Reddy",
    "Unguturu": "Puppala Srinivasarao",
    "V.Madugula": "Budi Mutyala Naidu",
    "Vemuru (SC)": "Merugu Nagarjuna",
    "Venkatagiri": "Anam Ramanarayana Reddy",
    "Vijayawada Central": "Vishnu Vardhan Malladi",
    "Vijayawada West": "Velam Palli Srinivasa Rao",
    "Vinukonda": "Bolla Brahma Naidu",
    "Vizianagaram": "Veera Bhadra Swamy Kolagatla",
    "Yemmiganur": "K Chennakesava Reddy",
    "Yerragondapalem": "Audimulapu Suresh",
    "Addanki": "Bachina Chenchu Garataiah",
    "Chirala": "Amanchi Krishna Mohan",
    "Gannavaram": "Yarlagadda Venkatarao",
    "Guntur West": "Chandragiri Yesuratnam",
    "Hindupur": "Shaik Mohammed Iqbal",
    "Ichchapuram": "Piriya Sairaj",
    "Kondapi": "Madasi Venkaiah",
    "Kuppam": "Krishna Chandra Mouli",
    "Mandapeta": "Pilli Subhas Chandra Bose",
    "Palacole": "Dr. Satyanarayana Murty Chavatapalli @dr.Babji",
    "Parchur": "Daggubati Venkateswara Rao",
    "Peddapuram": "Thota Saraswathi Ane Vani",
    "Rajahmundry City": "Routhu Surya Prakasa Rao",
    "Rajamundry Rural": "Akula Veerraju",
    "Razole": "Rajeswara Rao Bonthu",
    "Repalle": "Venkata Ramana Rao Mopidevi",
    "Tekkali": "Perada Tilak",
    "Undi": "P V L Narasimha Raju",
    "Uravakonda": "Y. Visweswara Reddy",
    "Vijayawada East": "Boppana Bhava Kumar",
    "Visakhapatnam East": "Akkaramani Vijaya Nirmala",
    "Visakhapatnam North": "Kammila Kannaparaju (K.K. RAJU)",
    "Visakhapatnam South": "Dronamraju Srinivasa Rao",
    "Visakhapatnam West": "Vijay Prasad Malla"
  }; 